# Generated by Django 6.0.5 on 2026-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает исполнителя'), ('accepted', 'Принят исполнителем'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('waiting_confirmation', 'Ожидает подтверждения')], default='pending', max_length=20),
        ),
    ]
