# Generated by Django 6.0.5 on 2026-06-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_category_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.category'),
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='price_modifier',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
