# Generated by Django 6.0.5 on 2026-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subcategory_category_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
